services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $documentManager: '@doctrine_mongodb.odm.document_manager' # Injects the MongoDB Document Manager service

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\ScrapRecette:
        tags: ['console.command']
    App\Command\ImportJson:
        tags: ['console.command']
    App\Command\ImportJsonNoSqlCommand:
        tags: ['console.command']
