services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $documentManager: '@doctrine_mongodb.odm.document_manager'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\ScrapRecette:
        tags: ['console.command']
    App\Command\ImportJson:
        tags: ['console.command']
    App\Command\ImportJsonNoSqlCommand:
        tags: ['console.command']
